// Optional dev-only integration test. No dependencies are loaded by the public site.
// Set PLAYWRIGHT_MODULE to the installed playwright package path if not on NODE_PATH.
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
const base = 'http://127.0.0.1:4173/soloforge-tools/';
mkdirSync('.qa', { recursive: true });
const errors = [];
let checks = 0;
const check = (condition, message) => { assert.ok(condition, message); checks++; };
const wavFixture = () => {
  const sampleRate = 8000, frames = 8000, bytes = Buffer.alloc(44 + frames * 2);
  bytes.write('RIFF', 0); bytes.writeUInt32LE(bytes.length - 8, 4); bytes.write('WAVE', 8);
  bytes.write('fmt ', 12); bytes.writeUInt32LE(16, 16); bytes.writeUInt16LE(1, 20); bytes.writeUInt16LE(1, 22);
  bytes.writeUInt32LE(sampleRate, 24); bytes.writeUInt32LE(sampleRate * 2, 28); bytes.writeUInt16LE(2, 32); bytes.writeUInt16LE(16, 34);
  bytes.write('data', 36); bytes.writeUInt32LE(frames * 2, 40);
  for (let i = 0; i < frames; i++) bytes.writeInt16LE(Math.round(Math.sin(i / 12) * 6000), 44 + i * 2);
  return bytes;
};
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read','clipboard-write'] });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  const external = [];
  page.on('request', req => { if (!req.url().startsWith('http://127.0.0.1')) external.push(req.url()); });
  await page.goto(base + 'asset-listing-formatter/');
  check(await page.locator('#listingResults').isHidden(), 'listing has no initial output');
  await page.locator('#productName').fill('Forest Asset Pack');
  await page.locator('#productSummary').fill('森の素材集');
  await page.locator('#productContents').fill('tree.png\nrock.png');
  await page.locator('#productFormat').fill('PNG');
  await page.locator('#productTerms').fill('商用利用可');
  await page.locator('#productCredit').fill('任意');
  await page.getByRole('button', { name: '説明文案を作成' }).click();
  check(await page.locator('#listingResults').isVisible(), 'listing outputs visible');
  check((await page.locator('#boothOutput').inputValue()).includes('【内容物】\ntree.png'), 'BOOTH headings and content');
  check((await page.locator('#itchOutput').inputValue()).includes('CONTENTS\ntree.png'), 'itch headings and content');
  check(!(await page.locator('#itchOutput').inputValue()).includes('NOTES'), 'listing omits empty sections');
  await page.screenshot({ path: '.qa/asset-listing-formatter-result-1440.png', fullPage: true });
  await page.locator('#productName').fill('<img src=x onerror=alert(1)>');
  check(await page.locator('#listingResults').isHidden(), 'listing edit hides stale output');
  await page.getByRole('button', { name: '説明文案を作成' }).click();
  check(await page.locator('#listingResults img').count() === 0, 'listing free text never becomes markup');
  check((await page.locator('#boothOutput').inputValue()).startsWith('<img'), 'listing preserves plain text');
  await page.locator('[data-copy-output="booth"]').click();
  await page.waitForFunction(() => document.querySelector('#listingStatus').textContent.includes('コピー'));
  check((await page.evaluate(() => navigator.clipboard.readText())).startsWith('<img'), 'listing copy succeeds');
  await page.locator('#productName').fill('');
  await page.getByRole('button', { name: '説明文案を作成' }).click();
  check((await page.locator('#listingStatus').textContent()).includes('商品名'), 'listing validates product name');
  await page.goto(base + 'game-audio-loop-tester/');
  check(await page.locator('#playLoop').isDisabled(), 'audio loop play starts disabled');
  await page.locator('#audioFile').setInputFiles({ name: 'loop.mp3', mimeType: 'audio/mpeg', buffer: Buffer.from('not audio') });
  check((await page.locator('#audioStatus').textContent()).includes('初版はWAV'), 'audio loop rejects non-WAV');
  await page.locator('#audioFile').setInputFiles({ name: 'loop.wav', mimeType: 'audio/wav', buffer: Buffer.from('invalid wav') });
  await page.waitForFunction(() => document.querySelector('#audioStatus').textContent.includes('このブラウザでは'));
  check(await page.locator('#playLoop').isDisabled(), 'audio loop decode failure stays disabled');
  await page.locator('#audioFile').setInputFiles({ name: 'loop.wav', mimeType: 'audio/wav', buffer: wavFixture() });
  await page.waitForFunction(() => document.querySelector('#audioStatus').textContent.includes('準備できました'));
  check(await page.locator('#playLoop').isEnabled(), 'audio loop valid WAV ready');
  await page.locator('#segmentSeconds').selectOption('1');
  check((await page.locator('#audioStatus').textContent()).includes('確認区間を更新'), 'audio loop segment update');
  await page.locator('#playLoop').click();
  check((await page.locator('#audioStatus').textContent()).includes('繰り返し再生'), 'audio loop playback starts');
  await page.locator('#stopLoop').click();
  check((await page.locator('#audioStatus').textContent()).includes('もう一度確認'), 'audio loop playback stops and can replay');
  await page.goto(base + 'subtitle-reading-speed/');
  check(await page.locator('#subtitleResults').isHidden(), 'subtitle has no initial result');
  await page.locator('#subtitleText').fill('字'.repeat(20));
  await page.locator('#displaySeconds').fill('5');
  await page.getByRole('button', { name: '読み速度を確認', exact: false }).click();
  check(await page.locator('#characterCount').textContent() === '20', 'subtitle character count');
  check(await page.locator('#cps').textContent() === '4.0', 'subtitle CPS');
  check(await page.locator('#speedLabel').textContent() === '標準的な範囲', 'subtitle standard band');
  check(await page.locator('#timeGuide').textContent() === '約3.4〜5.0秒', 'subtitle time guide rounds up');
  await page.locator('#subtitleText').fill('👨‍👩‍👧‍👦\n😀 A');
  await page.locator('#displaySeconds').fill('1');
  await page.getByRole('button', { name: '読み速度を確認', exact: false }).click();
  check(await page.locator('#characterCount').textContent() === '4', 'subtitle graphemes and newline');
  check(await page.locator('#speedLabel').textContent() === '標準的な範囲', 'subtitle Unicode result');
  await page.locator('#displaySeconds').fill('0');
  check(await page.locator('#subtitleResults').isHidden(), 'subtitle edit hides stale result');
  await page.getByRole('button', { name: '読み速度を確認', exact: false }).click();
  check((await page.locator('#inputStatus').textContent()).includes('0より大きい'), 'subtitle invalid seconds error');
  await page.locator('#displaySeconds').fill('2');
  await page.getByRole('button', { name: '読み速度を確認', exact: false }).click();
  check(await page.locator('#subtitleResults').isVisible(), 'subtitle valid recovery');
  await page.goto(base + 'monitor-ppi/');
  await page.waitForFunction(() => document.querySelector('#comparison').textContent.includes('26.6%'));
  check(await page.locator('#aPpi').textContent() === '108.8', 'PPI default A');
  check(await page.locator('#bPpi').textContent() === '137.7', 'PPI default B');
  check(await page.locator('#aPitch').textContent() === '0.233', 'pixel pitch default A');
  check((await page.locator('#comparison').textContent()).includes('画素密度が約26.6%高い'), 'PPI comparison is primary');
  check(await page.locator('#connectionNext').isVisible(), '4K next action visible');
  check(await page.locator('#connectionNext a').getAttribute('href') === '/soloforge-tools/display-bandwidth/', 'PPI links to display checker');
  await page.locator('#bPreset').selectOption('34-uwqhd');
  check(await page.locator('#bPpi').textContent() === '109.7', 'UWQHD preset');
  check((await page.locator('#comparison').textContent()).includes('ほぼ同じ'), 'near density wording');
  await page.locator('#aPreset').selectOption('32-4k'); await page.locator('#bPreset').selectOption('32-4k');
  check((await page.locator('#comparison').textContent()).includes('同じ画素密度'), 'same density wording');
  await page.locator('#aPreset').selectOption('27-wqhd'); await page.locator('#bPreset').selectOption('32-wqhd');
  check((await page.locator('#comparison').textContent()).includes('画素密度が約15.6%低い'), 'lower density wording');
  await page.locator('#bDiagonal').fill('');
  check(await page.locator('#ppiResults').isHidden(), 'empty PPI input hides stale result');
  check(await page.locator('#inputStatus').textContent() === '', 'empty PPI input waits without error');
  await page.locator('#bDiagonal').fill('0');
  check((await page.locator('#inputStatus').textContent()).includes('対角インチ'), 'zero diagonal error');
  await page.locator('#bDiagonal').fill('32'); await page.locator('#bWidth').fill('1920.5');
  check((await page.locator('#inputStatus').textContent()).includes('整数'), 'fractional pixel error');
  await page.locator('#bWidth').fill('100001');
  check((await page.locator('#inputStatus').textContent()).includes('100,000'), 'huge pixel error');
  await page.locator('#bPreset').selectOption('32-4k');
  check(await page.locator('#ppiResults').isVisible(), 'PPI valid preset recovery');
  await page.screenshot({ path: '.qa/monitor-ppi-desktop.png', fullPage: true });
  await page.goto(base + 'display-bandwidth/');
  await page.waitForFunction(() => document.querySelector('#bandwidth').textContent === '35.83');
  check(await page.locator('.link-result').count() === 13, 'all link classes rendered');
  check((await page.locator('#recommendation').textContent()).includes('FRL 48'), 'useful default result');
  await page.screenshot({ path: '.qa/display-desktop.png', fullPage: true });
  await page.locator('#shareBtn').click();
  await page.waitForFunction(() => document.querySelector('#shareStatus').textContent.includes('コピー'));
  check((await page.locator('#shareStatus').textContent()).includes('コピーしました'), 'display copy success');
  check((await page.evaluate(() => navigator.clipboard.readText())).includes('35.831808'), 'clipboard includes precise active bandwidth');
  await page.getByRole('button', { name: 'UWQHD 165Hz', exact: true }).click();
  check(await page.locator('#bandwidth').textContent() === '24.52', 'preset updates');
  check((await page.locator('.link-result').filter({ hasText: 'HBR3 ·' }).locator('.badge').textContent()) === '条件付き', 'near-boundary HBR3');
  await page.locator('#resolution').selectOption('custom');
  await page.locator('#width').fill('');
  check(await page.locator('#displayResults').isHidden(), 'invalid result hidden');
  check(await page.locator('#comparison').textContent() === '', 'invalid comparison cleared');
  check(await page.locator('#shareBtn').isDisabled(), 'invalid result cannot copy');
  await page.locator('#width').fill('1920'); await page.locator('#height').fill('1080');
  await page.locator('#refresh').selectOption('60'); await page.locator('#depth').selectOption('8');
  check(await page.locator('#bandwidth').textContent() === '2.99', 'custom input recovers');
  await page.locator('#refresh').selectOption('custom'); await page.locator('#customRefresh').fill('59.94');
  check((await page.locator('#conditionSummary').textContent()).includes('59.94'), 'fractional refresh');
  await page.locator('#chroma').selectOption('420'); await page.locator('#width').fill('1921');
  check((await page.locator('#inputStatus').textContent()).includes('偶数'), 'subsampling validation');
  await page.getByRole('button',{name:'4K 144Hz / HDR',exact:true}).click();
  await page.locator('#dsc').selectOption('confirmed');
  check((await page.locator('.link-result').filter({hasText:'HBR3 ·'}).locator('.badge').textContent())==='条件付き','DSC conditional');
  await page.goto(base+'obs-storage/');
  await page.waitForFunction(()=>document.querySelector('#fileSize').textContent !== '—');
  check(await page.locator('#fileSize').textContent()==='54.43 GB','OBS original size');
  check(await page.locator('#recordingsFit').textContent()==='16本','OBS original capacity');
  check(await page.locator('#uploadTime').textContent()==='4時間45分','OBS original upload');
  await page.locator('#videoBitrate').fill('8'); await page.locator('#audioBitrate').fill('0'); await page.locator('#hours').fill('1');
  check(await page.locator('#fileSize').textContent()==='3.60 GB','OBS independent known size');
  await page.locator('#shareBtn').click();
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('コピー'));
  check((await page.locator('#status').textContent()).includes('コピーしました'),'OBS copy');
  await page.locator('#hours').fill('');
  check(await page.locator('#obsResults').isHidden(),'OBS empty input hides stale results');
  await page.locator('#hours').fill('0'); await page.locator('#minutes').fill('0');
  check(await page.locator('#obsResults').isHidden(),'OBS zero duration');
  await page.locator('#minutes').fill('60');
  check(await page.locator('#obsResults').isHidden(),'OBS minutes upper limit');
  await page.locator('#minutes').fill('30');
  check(await page.locator('#fileSize').textContent()==='1.80 GB','OBS valid recovery');
  await page.goto(base+'gpu-psu/');
  await page.waitForFunction(()=>document.querySelector('#overall').textContent!=='—');
  check((await page.locator('#overall').textContent())==='PSU確認必要','GPU safe default requires confirmation');
  await page.locator('#gpu').selectOption('rx-7800-xt');
  await page.locator('#psuWatts').fill('850');
  check((await page.locator('#overall').textContent())==='そのまま交換候補','GPU reference OK case');
  await page.locator('#eightPinCables').selectOption('1');
  check((await page.locator('#connectorBadge').textContent())==='不足','GPU connector shortage');
  check((await page.locator('#overall').textContent())==='PSU交換候補','GPU shortage overall');
  await page.locator('#gpu').selectOption('rtx-5090');
  check((await page.locator('#capacityBadge').textContent())==='不足','GPU capacity shortage');
  check(external.length===0,'local preview sends no analytics requests');
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({width,height:900});
    for (const route of ['', 'asset-listing-formatter/','game-audio-loop-tester/','subtitle-reading-speed/','monitor-ppi/','gpu-psu/','display-bandwidth/','obs-storage/','privacy.html','contact.html','affiliate.html','about.html','missing/deep/route']) {
      const response = await page.goto(base+route);
      check(response.status()===(route.startsWith('missing')?404:200),`route ${route} status`);
      if (route==='display-bandwidth/') await page.waitForFunction(()=>document.querySelector('#bandwidth').textContent !== '—');
      if (route==='gpu-psu/') await page.waitForFunction(()=>document.querySelector('#overall').textContent !== '—');
      if (route==='monitor-ppi/') await page.waitForFunction(()=>document.querySelector('#comparison').textContent.includes('%'));
      check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`no overflow ${width} ${route}`);
      check(await page.locator('h1').count()===1,`one h1 ${route}`);
      check(await page.evaluate(()=>[...document.querySelectorAll('input,select,textarea')].every(el=>el.labels?.length || el.getAttribute('aria-label'))),`labelled inputs ${route}`);
      if([1440,390].includes(width)&&['','asset-listing-formatter/','game-audio-loop-tester/','subtitle-reading-speed/','monitor-ppi/','gpu-psu/','display-bandwidth/','obs-storage/'].includes(route)) await page.screenshot({path:`.qa/${route?route.replace('/',''):'home'}-${width}.png`,fullPage:true});
    }
  }
  await page.setViewportSize({width:640,height:900});
  await page.goto(base+'display-bandwidth/');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'200% text zoom has no horizontal overflow');
  await page.goto(base+'game-audio-loop-tester/');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'audio loop 200% text zoom has no horizontal overflow');
  await page.goto(base+'asset-listing-formatter/');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'listing 200% text zoom has no horizontal overflow');
  await page.goto(base+'monitor-ppi/');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'PPI 200% text zoom has no horizontal overflow');
  await page.goto(base+'subtitle-reading-speed/');
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'subtitle 200% text zoom has no horizontal overflow');
  await page.goto(base);
  await page.keyboard.press('Tab');
  check(await page.evaluate(()=>document.activeElement.className==='skip-link'),'keyboard skip link first');
  await page.keyboard.press('Enter');
  check(await page.evaluate(()=>location.hash==='#main'),'skip link navigates to main');
  check(errors.length===0,`JS errors: ${errors}`);
  await context.close();
  // Production-origin fixture: serve repository files locally and intercept GA completely.
  const trackingContext = await browser.newContext({permissions:['clipboard-write','clipboard-read']});
  await trackingContext.addInitScript(()=>Object.defineProperty(navigator,'webdriver',{get:()=>false}));
  const production = 'https://curren2766-star.github.io/soloforge-tools/';
  let gaLoads=0;
  await trackingContext.route('**/*',async route=>{
    const url=route.request().url();
    if(url.startsWith(production)){
      let file=new URL(url).pathname.slice('/soloforge-tools/'.length);if(file.endsWith('/')||file==='')file+='index.html';
      const contentType=file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html';
      await route.fulfill({body:readFileSync(file),contentType});
    } else { if(url.includes('googletagmanager'))gaLoads++; await route.fulfill({body:'',contentType:'text/javascript'}); }
  });
  const tracking = await trackingContext.newPage();
  const events = () => tracking.evaluate(()=>window.dataLayer.filter(x=>x[0]==='event').map(x=>({name:x[1],params:x[2]})));
  await tracking.goto(production+'gpu-psu/');
  await tracking.waitForFunction(()=>window.dataLayer.some(x=>x[0]==='config'));
  check((await events()).length===0,'GPU has no initial tool events');
  await tracking.locator('#psuWatts').fill('850');
  let gpuEvents=await events();
  check(gpuEvents.filter(x=>x.name==='tool_start').length===1,'GPU emits one start');
  check(gpuEvents.filter(x=>x.name==='tool_complete').length===1,'GPU emits one completion');
  check(gpuEvents.every(x=>Object.keys(x.params).join(',')==='tool'),'GPU analytics excludes inputs');
  for(const route of ['asset-listing-formatter/','game-audio-loop-tester/','subtitle-reading-speed/','monitor-ppi/','display-bandwidth/','obs-storage/']){
    await tracking.goto(production+route);
    await tracking.waitForFunction(()=>window.dataLayer.some(x=>x[0]==='config'));
    check((await events()).length===0,'no initial tool events');
    if(route==='asset-listing-formatter/'){
      await tracking.locator('#productName').fill('Secret product name');
      await tracking.locator('#productTerms').fill('Private license body');
      await tracking.getByRole('button',{name:'説明文案を作成'}).click();
    } else if(route==='game-audio-loop-tester/'){
      await tracking.locator('#audioFile').setInputFiles({name:'loop.wav',mimeType:'audio/wav',buffer:wavFixture()});
      await tracking.waitForFunction(()=>document.querySelector('#audioStatus').textContent.includes('準備できました'));
    } else if(route==='subtitle-reading-speed/'){
      await tracking.locator('#subtitleText').fill('テスト字幕です');
      await tracking.locator('#displaySeconds').fill('2');
      await tracking.getByRole('button',{name:'読み速度を確認',exact:false}).click();
    } else if(route==='monitor-ppi/'){
      await tracking.locator('#bPreset').selectOption('27-4k');
      await tracking.getByRole('button',{name:'画素密度を比較',exact:false}).click();
    } else if(route==='display-bandwidth/'){
      await tracking.locator('#depth').selectOption('8');
      await tracking.getByRole('button',{name:'接続条件をチェック',exact:false}).click();
    } else { await tracking.locator('#videoBitrate').fill('20');await tracking.locator('#calcBtn').click();await tracking.locator('#calcBtn').click(); }
    let emitted=await events();
    check(emitted.filter(x=>x.name==='tool_start').length===1,'one start per page session');
    check(emitted.filter(x=>x.name==='tool_complete').length===1,'deduplicated completion');
    if(['asset-listing-formatter/','display-bandwidth/','obs-storage/'].includes(route)){
      if(route==='asset-listing-formatter/') await tracking.locator('[data-copy-output="booth"]').click();
      else await tracking.locator('#shareBtn').click();
      await tracking.waitForFunction(()=>window.dataLayer.some(x=>x[0]==='event'&&x[1]==='result_share'));
      check((await events()).filter(x=>x.name==='result_share').length===1,'only successful copy tracked');
    }
    check((await events()).every(x=>Object.keys(x.params).join(',')==='tool'),'no input values in analytics');
  }
  await tracking.evaluate(()=>{
    const add=(href,slot)=>{const a=document.createElement('a');a.href=href;a.textContent=slot;a.dataset.affiliate=slot;document.body.append(a);};
    add('#','placeholder');add('/soloforge-tools/affiliate.html','internal');add('https://example.com/product','external');
  });
  await tracking.getByRole('link',{name:'placeholder',exact:true}).click();
  check(!(await events()).some(x=>x.name==='outbound_affiliate_click'),'placeholder never tracked');
  // Prevent navigation AFTER the shared document listener, retaining the captured event.
  await tracking.evaluate(()=>window.addEventListener('click',e=>e.preventDefault()));
  await tracking.getByRole('link',{name:'internal',exact:true}).click();
  check(!(await events()).some(x=>x.name==='outbound_affiliate_click'),'internal never tracked');
  await tracking.getByRole('link',{name:'external',exact:true}).click();
  check((await events()).filter(x=>x.name==='outbound_affiliate_click').length===1,'real external affiliate measured');
  check(gaLoads===7,'GA loaded once per page');
  const before=gaLoads;
  await tracking.goto(production+'display-bandwidth/?analytics=off');
  await tracking.waitForFunction(()=>document.querySelector('#bandwidth').textContent!=='—');
  check(gaLoads===before,'analytics off blocks GA loader');
  await trackingContext.close();
  console.log(`Browser QA passed: ${checks} checks, no JavaScript errors. Screenshots: .qa/`);
} finally { await browser.close(); }
